//! Try catch
const n1 =2;
const n2 =20;

try {
    console.log(n3);
} catch (error) {
    console.log(error);
}

console.log(n2);